version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"

  hass:
    container_name: hass
    image: homeassistant/home-assistant
    volumes:
      - /Users/jdruwe/Personal/hass/config:/config
    restart: always
    ports:
      - "8123:8123"

  node-red:
    container_name: node-red
    image: nodered/node-red-docker:v8
    volumes:
      - /Users/jdruwe/Personal/hass/node-red:/data
    environment:
      - PUID=501
      - PGID=20
    restart: always
    ports:
      - "1880:1880"

volumes:
  portainer_data: